import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

const GATEWAY_URL = 'https://connector-gateway.lovable.dev/google_calendar/calendar/v3';

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { topic, start_time, duration, student_name, student_names, teacher_name } = await req.json();

    const students: string[] = Array.isArray(student_names) && student_names.length > 0
      ? student_names
      : [student_name || 'Student'];

    if (!topic || !start_time) {
      return new Response(JSON.stringify({ error: 'topic and start_time are required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const lovableKey = Deno.env.get('LOVABLE_API_KEY');
    const calendarKey = Deno.env.get('GOOGLE_CALENDAR_API_KEY');
    if (!lovableKey) throw new Error('LOVABLE_API_KEY is not configured');
    if (!calendarKey) throw new Error('GOOGLE_CALENDAR_API_KEY is not configured');

    const startDate = new Date(start_time);
    const endDate = new Date(startDate.getTime() + (duration || 60) * 60 * 1000);

    const requestId = `k2k-${crypto.randomUUID()}`;

    const eventBody = {
      summary: topic,
      description: `Kid2Kid CS lesson between ${teacher_name || 'Teacher'} and ${student_name || 'Student'}.`,
      start: { dateTime: startDate.toISOString(), timeZone: 'UTC' },
      end: { dateTime: endDate.toISOString(), timeZone: 'UTC' },
      conferenceData: {
        createRequest: {
          requestId,
          conferenceSolutionKey: { type: 'hangoutsMeet' },
        },
      },
    };

    const gcalResponse = await fetch(
      `${GATEWAY_URL}/calendars/primary/events?conferenceDataVersion=1`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${lovableKey}`,
          'X-Connection-Api-Key': calendarKey,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(eventBody),
      }
    );

    const gcalData = await gcalResponse.json();
    if (!gcalResponse.ok) {
      throw new Error(`Google Calendar API failed [${gcalResponse.status}]: ${JSON.stringify(gcalData)}`);
    }

    const meetLink: string | undefined =
      gcalData.hangoutLink ||
      gcalData.conferenceData?.entryPoints?.find((e: any) => e.entryPointType === 'video')?.uri;

    if (!meetLink) {
      throw new Error('Google Meet link was not generated by Calendar API');
    }

    // Save to database (reuse existing zoom_* columns to store the Meet link)
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

    const rows = students.map((s) => ({
      teacher_name: teacher_name || 'Teacher',
      student_name: s,
      scheduled_date: start_time.split('T')[0],
      scheduled_time: start_time.split('T')[1]?.substring(0, 5) || '00:00',
      zoom_meeting_id: gcalData.id,
      zoom_join_url: meetLink,
      zoom_start_url: meetLink,
      zoom_password: null,
      status: 'scheduled',
    }));

    const dbResponse = await fetch(`${supabaseUrl}/rest/v1/meetings`, {
      method: 'POST',
      headers: {
        'apikey': supabaseKey,
        'Authorization': `Bearer ${supabaseKey}`,
        'Content-Type': 'application/json',
        'Prefer': 'return=representation',
      },
      body: JSON.stringify(rows),
    });

    const dbData = await dbResponse.json();
    if (!dbResponse.ok) {
      throw new Error(`DB insert failed [${dbResponse.status}]: ${JSON.stringify(dbData)}`);
    }

    return new Response(JSON.stringify({
      success: true,
      meetings: dbData,
      meeting: dbData[0],
      count: dbData.length,
      meet: {
        event_id: gcalData.id,
        join_url: meetLink,
        html_link: gcalData.htmlLink,
      },
    }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error: unknown) {
    console.error('Error creating Google Meet:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(JSON.stringify({ success: false, error: errorMessage }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
